### ISSUE TITLE
[Discussion] Color theme

### ISSUE THREAD

**Issue by Hacksore** [Norfeldt/github-issue-reactions-browser-extension#22]
I love this extension very much as it helps me sift through big issues.

One thing I'd like to discuss is the use of @wesbos yellow which does not really fit well on github. Would you be opposed to using a dark/light theme color that matches github or allow the user to control them?

Quick mock up with slightly more on theme colors.
![image](https://user-images.githubusercontent.com/996134/219873437-aa302580-4a97-41fa-a92c-acb1b75fb7cd.png)

**Comment by Hacksore** [comment]
Personally I've accepted that as the github/emoji standard style but the controls on the other hand should be consistent with github overall style.

**Comment by purplespider** [comment]
I agree with this, actually. I know it's a small thing, but it would be nice if the extension could better fit in with GitHub's styles. e.g. by inheriting and/or using their class names. Would make it feel less "clunky". e.g.

**Before & After:**
<img width="349" alt="Screenshot 2023-03-02 at 10 08 44@2x" src="https://user-images.githubusercontent.com/329880/222398082-d66ddfa8-fced-4139-b8eb-1f69e08d9184.png"><img width="350" alt="Screenshot 2023-03-02 at 10 25 20@2x" src="https://user-images.githubusercontent.com/329880/222401984-d4baf934-8088-4029-b876-f8dadf3d1bf9.png">
Note:
* "Reactions" heading matches other GitHub sidebar headings (Classes: `discussion-sidebar-heading text-bold`)
* Addition of dividing line, like other sidebar sections. (From: `.discussion-sidebar-item+.discussion-sidebar-item`)
* Adjustment of "by" text to match GitHub sizing. (Inherited automatically if this was a `p` instead of a `div`).
* etc

**Comment by wesbos** [comment]
I agree (though I am flattered by Cobalt2) - it should use the github CSS variables. 

var(--color-fg-default)
--color-social-reaction-bg-hover

**Comment by Hacksore** [comment]
PR is up! Thanks @wesbos for getting the colors, true MVP.
